# -*- coding: utf-8 -*-
"""DIP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iLTGoTwMrXvUZKPLmUylVOD5RXe8N3K
"""

from google.colab.patches import cv2_imshow
import numpy as np
import cv2

"""Defining Replication function"""

def scale_replication(img, scale_factor):
    # Scaling down by replication
    new_width = int(img.shape[1] * scale_factor)
    new_height = int(img.shape[0] * scale_factor)
    scaled_img = np.zeros((new_height, new_width, 3), np.uint8)
    for y in range(new_height):
        for x in range(new_width):
         original_x = int(x / scale_factor)
         original_y = int(y / scale_factor)
         scaled_img[y, x] = img[original_y, original_x]
    return scaled_img

"""Defining Interpolation function"""

def scale_interpolation(img, scale_factor):
    # Scaling by interpolation
    rows, cols = img.shape
    scaled_rows, scaled_cols = int(rows * scale_factor), int(cols * scale_factor)
    scaled_img = cv2.resize(img, (scaled_cols, scaled_rows),interpolation=cv2.INTER_CUBIC)
    return scaled_img

"""Main program

"""

img= cv2.imread('lena_color.tif',0)

if img is None:
    print("image not found")
    exit()

while True:
    print("\n****MENU***")
    print("Press 1 for showing image")
    print("Press 2 for scaling image by replication")
    print("Press 3 for scaling image by interpolation")
    print("Press 4 to Exit")
    ch =int(input("#Enter the Choice: "))

    if ch==1:
      cv2_imshow(img)
      cv2.waitKey(0)

    elif ch==2:
        print("\n********")
        print("Press 1 to scale up ")
        print("Press 2 to scale down ")
        ch2 = int(input("Enter the Choice: "))
        if ch2==1:
            sf=float(input("Enter scale factor: "))
            img1= scale_replication(img,sf)
            cv2_imshow(img1)
            cv2.waitKey(0)
        elif ch2==2:
            sf=float(input("Enter scale factor: "))
            img1= scale_replication(img,1/sf)
            cv2_imshow(img1)
            cv2.waitKey(0)

    elif ch==3:
        print("\n*******")
        print("Press 1 to scale up ")
        print("Press 2 to scale down ")
        ch2 = int(input("Enter the Choice: "))
        if ch2==1:
            sf=float(input("Enter scale factor: "))
            img2= scale_interpolation(img,sf)
            cv2_imshow(img1)
            cv2.waitKey(0)
        elif ch2==2:
            sf=float(input("Enter scale factor: "))
            img2= scale_interpolation(img,1/sf)
            cv2_imshow(img2)
            cv2.waitKey(0)

    elif ch==4:
        cv2.destroyAllWindows()
        exit()